fix handling of multiple huge page sizes
If multiple huge pages sizes were requested it could happen that some of
them had no valid hugetlbfs mountpoint (LP: #1557532).
To solve that dpdk-init had to learn to understand what the default huge
page size is and to take care of mounting this and/or any other size
depending on the requested hugepages in dpdk.conf.

diff --git a/debian/dpdk-init b/debian/dpdk-init
--- a/debian/dpdk-init
+++ b/debian/dpdk-init
@@ -23,33 +23,103 @@ set -e
 DPDK_BIND="/sbin/dpdk_nic_bind"
 DPDK_INTERF="/etc/dpdk/interfaces"
 
-#
-# The DPDK library will use the first mounted instance it finds. So
-# if there is already one, there is no need to create another.
-#
-hugetlbfs_mountpoint() {
-    local hugetlbfsmp
-    hugetlbfsmp=$(grep "hugetlbfs" /proc/mounts |sed -n '1p' \
-        | sed -e 's/^ *[^ ]* //; s/ .*//g')
-    echo "${hugetlbfsmp}"
+
+# pagesize supports [G|g]/[M|m]/[K|k]
+get_kbytes() {
+    local unit
+    local num
+    unit=$(echo "${1}" | sed 's/[0-9]*//g')
+    num=$(echo "${1}" | sed 's/[^0-9]*//g')
+    case ${unit} in
+    *g | *G)
+        echo $((num*1024*1024))
+        ;;
+    *m | *M)
+        echo $((num*1024))
+        ;;
+    *k | *K)
+        echo $((num))
+        ;;
+    *)
+        echo $((num/1024))
+        ;;
+    esac
 }
 
-mount_hugetlbfs() {
-    if [ "$(hugetlbfs_mountpoint)" != "" ]; then
-        return 0
-    fi
-    MNT=/dev/hugepages
+get_default_hpgsz() {
+    default_hpgsz=$(grep "Hugepagesize:" /proc/meminfo \
+        | sed 's/^Hugepagesize:\s*//g' | sed 's/\s*kB$//g')
+    echo "${default_hpgsz}"
+}
 
-    if [ ! -e $MNT ]; then
-        mkdir $MNT
+get_hugetlbfs_mountpoint() {
+    local requested_hpgsz
+    local mp_hpgsz
+    requested_hpgsz=$(get_kbytes "${1}")
+
+    grep hugetlbfs /proc/mounts | while read \
+        mntfrom mntpoint mntfstype mntopt mntdump mntfsck; do
+
+        # check if the current muntpoint is of the requested huge page size
+        case ${mntopt} in
+        *pagesize=*)
+            mp_hpgsz=$(echo "${mntopt}" | sed 's/.*pagesize=//g' | sed 's/,.*//g')
+            mp_hpgsz=$(get_kbytes "${mp_hpgsz}")
+            ;;
+        *)
+            mp_hpgsz=$(get_default_hpgsz)
+            ;;
+        esac
+        if [ "${requested_hpgsz}" -eq "${mp_hpgsz}" ]; then
+            echo "${mntpoint}"
+            return
+        fi
+    done
+}
+
+_mount_hugetlbfs() {
+    local MNT="/dev/hugepages"
+    local MNTOPTS=""
+    local requested_hpgsz
+    local default_hpgsz
+    requested_hpgsz=$(get_kbytes "${1}")
+    default_hpgsz=$(get_default_hpgsz)
+
+    # special case if this is not the default huge page size
+    if [ "${requested_hpgsz}" -ne "${default_hpgsz}" ]; then
+        MNT="${MNT}-${requested_hpgsz}"
+        MNTOPTS="pagesize=${requested_hpgsz}K"
+    fi
+
+    if [ ! -e "${MNT}" ]; then
+        mkdir "${MNT}"
         if [ $? -ne 0 ]; then
-            echo "Could not create directory $MNT!" >&2
+            echo "Could not create directory ${MNT}!" >&2
             return 1
         fi
     fi
-    mount -thugetlbfs hugetlbfs $MNT
-
+    mount -thugetlbfs hugetlbfs "${MNT}" -o "${MNTOPTS}"
     return $?
+}
+
+#
+# The DPDK library will use the first mounted instance it finds for a given
+# page size. so if there is already one for a given size there is no need to
+# create another for the same huge page size.
+#
+mount_hugetlbfs() {
+    if [ ! -r /etc/dpdk/dpdk.conf ]; then
+        return 1
+    fi
+    . /etc/dpdk/dpdk.conf
+
+    # if a page size is requested, there has to be a mountpoint for that size
+    if [ -n "${NR_2M_PAGES}" -a -z "$(get_hugetlbfs_mountpoint '2M')" ]; then
+        _mount_hugetlbfs 2M
+    fi
+    if [ -n "${NR_1G_PAGES}" -a -z "$(get_hugetlbfs_mountpoint '1G')" ]; then
+        _mount_hugetlbfs 1G
+    fi
 }
 
 _setup_hugepages() {
